server:
  port: 8080

spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymart_dev_db
    username: root
    password: rootuser

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: amishakhunte60@gmail.com
    password: yvuw dwzd lbht dsty
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


razorpay:
  key:
    id: rzp_test_Sts4ErOLa4LYpS
    secret: dTmJ7gqydC4LCIXmbkrrqVJ3















app:
  images:
    upload-dir: C:/Users/amish/Downloads/ecommerce-backend-uploads
